% specify the vertices in the same order as it is given in the problem definition - it is needed for the tests
x0=[-2,4];              %first vertex of the starting simplex - two dimensional row vector
x1=[-1,4];              %second vertex of the starting simplex - two dimensional row vector
x2=[-1.5,5];            %third vertex of the starting simplex - two dimensional row vector
tolerance=10^(-2);      %tolerance for the size of the simplex
%-------------------------------------------------------------



%%%%%%%%%%%  draw level curves of the function %%%%%%%%%%%%
levelvalues=[0.08,0.2,0.5,1.2,2.0,3.5,5.0,7.,9.0,11.,14.,18,22,26,30.,34.,38.,43,53.,60.,70,80.,90,100,120,140.,170.,220.,270.,400.,550.,810.];
xinterval=[-3.,2.];
yinterval=[-1.5,5];
intx1=xinterval(1):0.05:xinterval(2);
inty1=yinterval(1):0.05:yinterval(2);
[xx,yy]=meshgrid(intx1,inty1);
zz=fv(xx,yy);
hold on
contour(xx,yy,zz,levelvalues,'b',LineWidth=1.5)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

simplex={x0,x1,x2};     %store the three vertices in a cell array - this represents the simplex
k=0;
while simplex_size(simplex)>=tolerance & k<100
    draw_simplex(simplex)
    simplex=vertex_sort(simplex);   %sort the vertices
    fprintf('step %2d:  simplex=[% 10.8f, % 10.8f],  [% 10.8f,% 10.8f],  [% 10.8f,% 10.8f],  % 6.4e, % 6.4e, % 6.4e\n',k,simplex{1},simplex{2},simplex{3},f(simplex{1}),f(simplex{2}),f(simplex{3})) 
    xc=(simplex{1}+simplex{2})/2;
    xr=2*xc-simplex{3};
    if f(xr)>=f(simplex{3})     %shrink the simplex to its half size
        simplex{2}=simplex{1}+0.5*(simplex{2}-simplex{1});
        simplex{3}=simplex{1}+0.5*(simplex{3}-simplex{1});
    else
        simplex{3}=xr;
    end
    k=k+1;
end
fprintf('step %2d:  simplex=[% 10.8f, % 10.8f],  [% 10.8f,% 10.8f],  [% 10.8f,% 10.8f],  % 6.4e, % 6.4e, % 6.4e\n',k,simplex{1},simplex{2},simplex{3},f(simplex{1}),f(simplex{2}),f(simplex{3})) 
output=(simplex{1}+simplex{2}+simplex{3})/3;
fprintf('minimum point p=[% 10.8f, % 10.8f],  f(p)=% 6.4e\n',output,f(output)) 

%%%%%%%%%% variables used for testing the code %%%%%%%%%%%%
output;   %the output of the iteration
x0;         %first vertex of the starting simplex
x1;         %second vertex of the starting simplex
x2;         %third vertex of the starting simplex
f1=f(x0);   %function value for testing the correctness of the definition of f
f2=f(x1);   %function value for testing the correctness of the definition of f
f3=f(x2);   %function value for testing the correctness of the definition of f
tolerance;  %tolerance value

function z=f(u)     %the function to be minimized, u is a two dimensional vector
    z=(u(1)^2-2*u(2))^2+2*(u(1)-1)^2;
end

function sorted_simplex=vertex_sort(simp)    %sort the vertices of the simplex simp in the order of the function values 
    fv=[f(simp{1}),f(simp{2}),f(simp{3})];   %vector of function values
    [sx,ind]=sort(fv);                       %sort the function values
    sorted_simplex=simp(ind);                %output the simplex in the order of the function values         
end    

function z=simplex_size(simp)                %compute the longest edge of the simplex simp
    z=max([norm(simp{1}-simp{2},Inf),norm(simp{1}-simp{3},Inf),norm(simp{2}-simp{3},Inf)]);
end

function z=fv(x,y)      %evaluate the function f at the points (x(i,j),y(i,j)), 
                        %where x and y are input matrices generated by meshgrid
                        %the output z is the matrix of the function values
    [n,m]=size(x);
    z=zeros(n,m);
    for i=1:n
        for j=1:m
            z(i,j)=f([x(i,j),y(i,j)]);
        end
    end
end

function draw_simplex(simp)      %draw the simplex simp
    plot([simp{1}(1),simp{2}(1),simp{3}(1)],[simp{1}(2),simp{2}(2),simp{3}(2)],'ro','linewidth',2)
    plot([simp{1}(1),simp{2}(1),simp{3}(1),simp{1}(1)],[simp{1}(2),simp{2}(2),simp{3}(2),simp{1}(2)],'r-','linewidth',2)
end
