% use row vectors in the iteration
x0=[-1,4];          % starting value of the sequence - two dimensional row vector
tolerance=0.005;  %tolerance
%----------------------------------------------------------

%%%%%%%%%%%  draw level curves of the function %%%%%%%%%%%%
levelvalues=[0.08,0.2,0.5,1.2,2.0,3.5,5.0,7.,9.0,11.,14.,18,22,26,30.,34.,38.,43,53.,60.,70,80.,90,100,120,140.,170.,220.,270.,400.,550.,810.];
xinterval=[-2.5,2.5];
yinterval=[-1.,4.5];
intx1=xinterval(1):0.05:xinterval(2);
inty1=yinterval(1):0.05:yinterval(2);
[xx,yy]=meshgrid(intx1,inty1);
zz=fv(xx,yy);
hold on
axis equal
contour(xx,yy,zz,levelvalues,'b',LineWidth=1.5)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

x=x0;       %current value of the sequence
y=x0-1;     %artificial previous element of the sequence
fprintf('Step  0,  x=[% 10.8f, % 10.8f],  f(x)=% 8.6e\n',x,f(x))
k=0;
while norm(x-y,2)>=tolerance & k<100
    y=x;
    v=df(y)/norm(df(y),2);      % normalized gradient vector
    alpha=simplex1d(y,v,tolerance/2);      % use 1D simplex method for minimization along the -v direction
    x=y-alpha*v;
    k=k+1;
    fprintf('Step %2d,  x=[% 10.8f, % 10.8f],  f(x)=% 8.6e\n',k,x,f(x))
    plot([y(1),x(1)],[y(2),x(2)],'-or','MarkerFaceColor','r','Linewidth',2)
end
output=x;
fprintf('minimum point=[% 10.8f,% 10.8f]\n',output) 

%%%%%%%%%% variables used for testing the code %%%%%%%%%%%%
output=x;   %the output of the iteration
x0;          %starting value of the sequence
tolerance;   %tolerance
f1=f(x0);    %function value for testing the correctness of the definition of f
f2=f(x0-1);   %function value for testing the correctness of the definition of f
f3=f(x0+1);   %function value for testing the correctness of the definition of f
df1=df(x0);   %function value for testing the correctness of the definition of df
df2=df(x0-1);   %function value for testing the correctness of the definition of df
df3=df(x0+1);   %function value for testing the correctness of the definition of df

function z=f(u)     %the function to be minimized, u is a two dimensional vector
    z=(u(1)^2-2*u(2))^2+2*(u(1)-1)^2;
end

function z=df(u)     %the gradient vector of the function f(u), z is a row vector
    z=[4*(u(1)^2-2*u(2))*u(1)+4*(u(1)-1),-4*(u(1)^2-2*u(2))];
end

function z=fv(x,y)      %evaluate the function f at the points (x(i,j),y(i,j)), 
                        %where x and y are input matrices generated by meshgrid
                        %the output z is the matrix of the function values
    [n,m]=size(x);
    z=zeros(n,m);
    for i=1:n
        for j=1:m
            z(i,j)=f([x(i,j),y(i,j)]);
        end
    end
end

function y=phi(t,p,v)
    y=f(p-t*v);
end

function alpha=simplex1d(p,v,epsilon)
% minimize the function phi(t)=f(p-t*v) for t>0 using 1D simplex method with tolerance epsilon
%use the starting simplex as the [0,1] interval
    x = 0;      % vertex of the simplex
    y = 1;      % vertex of the simplex
    k=0;
    %fprintf('   simplex1d %2d: [%2.10f,%2.10f], %2.10f, %2.10f\n',k,x,y,phi(x,p,v),phi(y,p,v));
    while (abs(y-x)>=epsilon) & k<100
        if phi(x,p,v)<phi(y,p,v),       % y is the worst vertex
            temp = 2.*x-y;              % reflected vertex
            y = x;
            if phi(temp,p,v)<phi(y,p,v), 
                x = temp;               % accept reflection
            else
                x = (x+temp)/2.;        % contract to half
            end
        else
            temp = 2*y-x;
            x = y;
            if phi(temp,p,v)<phi(x,p,v), 
                y = temp;
            else
                y = (y+temp)/2.;
            end
        end
        k=k+1;
        %fprintf('   simplex1d %2d: [%2.10f,%2.10f], %2.10f, %2.10f\n',k,x,y,phi(x,p,v),phi(y,p,v));
    end
    alpha=(x+y)/2;
end
